AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ApiGwExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "ApiGwExecutionPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "LambdaExecutionPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:*"
                  - "secretsmanager:GetSecretValue"
                Resource: "*"

  BillingApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: BillingApi
      StageName: Dev
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: './api.yaml'
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      Cors:
        AllowMethods: "'POST, GET, PUT, DELETE'"
        AllowHeaders: "'X-Forwarded-For', 'X-Webhook-Secret'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"

  CreateInvoice:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: CreateInvoice
      CodeUri: src/billing-api/functions/create-invoice/
      Handler: app.handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 60
      Tracing: Active
      Role: !GetAtt LambdaExecutionRole.Arn

  GetInvoices:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: GetInvoices
      CodeUri: src/billing-api/functions/get-all-invoices/
      Handler: app.handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 60
      Tracing: Active
      Role: !GetAtt LambdaExecutionRole.Arn

  GetInvoice:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: GetInvoice
      CodeUri: src/billing-api/functions/get-invoice/
      Handler: app.handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 60
      Tracing: Active
      Role: !GetAtt LambdaExecutionRole.Arn

  UpdateInvoice:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: UpdateInvoice
      CodeUri: src/billing-api/functions/update-invoice/
      Handler: app.handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 60
      Tracing: Active
      Role: !GetAtt LambdaExecutionRole.Arn

  DeleteInvoice:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: DeleteInvoice
      CodeUri: src/billing-api/functions/delete-invoice/
      Handler: app.handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 60
      Tracing: Active
      Role: !GetAtt LambdaExecutionRole.Arn

Outputs:
  BillingApi:
    Description: "API Gateway endpoint URL for Dev stage for Billing API"
    Value: !Sub "https://${BillingApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/billing"
  CreateInvoice:
    Description: "CreateInvoice Lambda Function ARN"
    Value: !GetAtt CreateInvoice.Arn
  GetInvoices:
    Description: "GetInvoices Lambda Function ARN"
    Value: !GetAtt GetInvoices.Arn
  GetInvoice:
    Description: "GetInvoice Lambda Function ARN"
    Value: !GetAtt GetInvoice.Arn
  UpdateInvoice:
    Description: "UpdateInvoice Lambda Function ARN"
    Value: !GetAtt UpdateInvoice.Arn
  DeleteInvoice:
    Description: "DeleteInvoice Lambda Function ARN"
    Value: !GetAtt DeleteInvoice.Arn
