AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  BillingApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: BillingApi
      StageName: Dev
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: './api.yaml'
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      Cors:
        AllowMethods: "'POST, GET, PUT, DELETE'"
        AllowHeaders: "'X-Forwarded-For', 'X-Webhook-Secret'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"

  CreateInvoice:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: CreateInvoice
      CodeUri: src/billing-api/functions/create-invoice/
      Handler: app.handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 60
      Tracing: Active
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - logs:*
            Resource: "*"
        - Statement:
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: arn:aws:secretsmanager:us-east-2:YOUR_ACCOUNT_ID:secret:infra-revelium-mongo-SzisXB

  GetInvoices:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: GetInvoices
      CodeUri: src/billing-api/functions/get-all-invoices/
      Handler: app.handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 60
      Tracing: Active
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - logs:*
            Resource: "*"
        - Statement:
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: arn:aws:secretsmanager:us-east-2:YOUR_ACCOUNT_ID:secret:infra-revelium-mongo-SzisXB

  GetInvoice:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: GetInvoice
      CodeUri: src/billing-api/functions/get-invoice/
      Handler: app.handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 60
      Tracing: Active
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - logs:*
            Resource: "*"
        - Statement:
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: arn:aws:secretsmanager:us-east-2:YOUR_ACCOUNT_ID:secret:infra-revelium-mongo-SzisXB

  UpdateInvoice:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: UpdateInvoice
      CodeUri: src/billing-api/functions/update-invoice/
      Handler: app.handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 60
      Tracing: Active
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - logs:*
            Resource: "*"
        - Statement:
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: arn:aws:secretsmanager:us-east-2:YOUR_ACCOUNT_ID:secret:infra-revelium-mongo-SzisXB

  DeleteInvoice:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: DeleteInvoice
      CodeUri: src/billing-api/functions/delete-invoice/
      Handler: app.handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 60
      Tracing: Active
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - logs:*
            Resource: "*"
        - Statement:
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: arn:aws:secretsmanager:us-east-2:YOUR_ACCOUNT_ID:secret:infra-revelium-mongo-SzisXB

Outputs:
  BillingApi:
    Description: "API Gateway endpoint URL for Dev stage for Billing API"
    Value: !Sub "https://${BillingApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/billing"
  CreateInvoice:
    Description: "CreateInvoice Lambda Function ARN"
    Value: !GetAtt CreateInvoice.Arn
  GetInvoices:
    Description: "GetInvoices Lambda Function ARN"
    Value: !GetAtt GetInvoices.Arn
  GetInvoice:
    Description: "GetInvoice Lambda Function ARN"
    Value: !GetAtt GetInvoice.Arn
  UpdateInvoice:
    Description: "UpdateInvoice Lambda Function ARN"
    Value: !GetAtt UpdateInvoice.Arn
  DeleteInvoice:
    Description: "DeleteInvoice Lambda Function ARN"
    Value: !GetAtt DeleteInvoice.Arn
